### ISSUE TITLE
求助。卡在了fastboot

### ISSUE THREAD

**Issue by al-mark-net** [jialeicui/open-lx01#10]
系统: ubuntu 22.04 , 6.5.0-14-generic
fastboot安装尝试：
1. `sudo apt install fastboot`。(fastboot version 28.0.2-debian)
2. 使用的链接下载，然后复制fastboot到/usr/bin。(fastboot version 34.0.5-10900879) 
现象：
1. sunxi#fastboot_test
    run usb fastboot
    sunxi_fastboot_init
    recv addr 0x41000000
    send addr 0x45260410
    delay time 0
    usb init ok
    set address 0x8 （这行没有）
2. 另外一个终端执行 `fastboot devices` 没有任何显示 。 
     执行 `fastboot flash rootfs1 rootfs.img` 显示 wait for devices。   
纯小白，网上找了一圈，还是不得要领。请教是什么地方出现问题了？

**Comment by jialeicui** [comment]
您的音箱是小爱mini对吧?   
linux 下的话, 能否试下用 sudo 执行 fastboot ?

**Comment by al-mark-net** [comment]
试过了，sudo fastboot devices 也是没有任何显示

**Comment by jialeicui** [comment]
如果还不行的话，可以依次确认一下：
- 确认下USB线是ok的，有的线只有充电的功能（找个老安卓手机之类的试试能不能传东西）
- 执行 lsusb 看下是不是有相关的设备
- 确认音箱供电是否正常，如果插在 USB hub 上的话可能供电不足（调试的时候可以把喇叭拔掉）
- `sudo dmesg -w` 一直开着，看切换到 fastboot 模式的时候有什么新增日志

（家里的音箱root之后再刷固件就不用串口了，所以把音箱组装起来了，抱歉现在没办法测试）

**Comment by al-mark-net** [comment]
win10不会安装google usb驱动。 没有安装驱动，直接用`fastboot devices`也是没有信息显示。

---

我是用的USB 转 TTL 的刷机线直连电脑。供电是原装电源

---

`lsusb`
Bus 001 Device 010: ID 1a86:7523 QinHeng Electronics CH340 serial converter

---

`sudo dmesg -w`, 插拔 USB, 打印的日志
[ 1111.278942] usb 1-3: new full-speed USB device number 9 using xhci_hcd
[ 1111.428593] usb 1-3: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.64
[ 1111.428611] usb 1-3: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[ 1111.428619] usb 1-3: Product: USB Serial
[ 1111.431756] usb_ch341 1-3:1.0: ttyCH341USB0: ch341 USB device

[ 1292.225713] usb 1-3: USB disconnect, device number 9
[ 1292.226542] usb_ch341 1-3:1.0: ch341 usb device disconnect.

---

连接lx01 `screen /dev/ttyCH341USB0 115200` (是否这里出错了？)

**Comment by al-mark-net** [comment]
原来系统自带的ch341.ko识别不了设备，然后我：
1. 下载新的ch341驱动 https://www.wch.cn/download/CH341SER_LINUX_ZIP.html
2. make
3. 给驱动签名 
    - 安装依赖
        - sudo apt install mokutil
        - sudo apt install shim-signed
        - sudo update-secureboot-policy --new-key
    - 导入签名证书
        - sudo mokutil --import /var/lib/shim-signed/mok/MOK.der
    - 重启，UEFI询问是否要更改安全设置，选择yes。选择Enroll MOK。
    - 将签名写入驱动
        - sudo /usr/src/linux-headers-6.5.0-14-generic/scripts/sign-file sha256 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der ch341.ko
4. sudo make load
5. 移动到系统默认驱动目录 sudo scp ch341.ko /lib/modules/6.5.0-14-generic/kernel/drivers/usb/serial/
6. 开机自动加载驱动 sudo depmod
7. 解决端口权限
    a. sudo chmod 777 /dev/ttyCH341USB0
    b. sudo usermod -aG dialout al
8. 连接设备 screen /dev/ttyCH341USB0 115200

**Comment by jialeicui** [comment]
我的文档可能没有说清楚，fastboot刷机的时候除了 USB转串口是用来串口输出(只是用来看日志和进uboot)以外，供电的那个 micro USB 接口是用来 fastboot 刷机用的
也就是说你要用一个可以传输数据的 micro USB线插到电脑的USB口，不能用原装电源

**Comment by jialeicui** [comment]
```
               micro-USB
      +--------------------+
      |                    |
      |                    |
      |                    |
+-----+----+          +----v----+
|          | USB-ttl  |         |
|   LX01   +---------->   PC    |
|          |          |         |
+----------+          +---------+
```

**Comment by jialeicui** [comment]
> win10不会安装google usb驱动。 没有安装驱动，直接用`fastboot devices`也是没有信息显示。

windows 不安装驱动应该是没办法用 fastboot 的，安装方式按官网的来就行：https://developer.android.com/studio/run/oem-usb#InstallingDriver

**Comment by al-mark-net** [comment]
我太小白了。OMG
可以刷机，谢谢

**Comment by al-mark-net** [comment]
我这设备管理器没有发现设备。。只有发现的端口
后来还安装了android studio, 在里面安装的google usb驱动和command line。不过我看command line文件夹里面好像没有fastboot,就没有继续。。

**Comment by jialeicui** [comment]
嗯，折腾折腾就熟悉了，如果没问题我关issue了哈，有啥问题继续append或者提新的

**Comment by al-mark-net** [comment]
恩，谢谢

**Comment by Lanceliyp** [comment]
> ```
>                micro-USB
>       +--------------------+
>       |                    |
>       |                    |
>       |                    |
> +-----+----+          +----v----+
> |          | USB-ttl  |         |
> |   LX01   +---------->   PC    |
> |          |          |         |
> +----------+          +---------+
> ```

用了一条不正确的数据线，折腾两天，感谢~~
